version: "3.4"

services:
  straight-back:
    image: straight-back
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
